### ISSUE TITLE
LangFuse v3.66.1 Docker Setup Issues - ClickHouse Configuration Failures

### ISSUE THREAD

**Issue by ahelme** [qarumba/academia-os#32]
## Issue Summary
LangFuse v3.66.1 containers fail to start properly due to ClickHouse configuration and database migration issues, preventing AI monitoring functionality in AcademiaOS.

## Current Behavior
- LangFuse server container enters restart loop
- ClickHouse migration failures cause container exits
- Database URL parsing errors when attempting to disable ClickHouse
- Health check fails: `curl: (7) Failed to connect to localhost port 3030`

### Container Status
```bash
docker ps | grep langfuse
# Shows: Restarting (1) X seconds ago
```

### LangFuse Server Logs
```
Applying clickhouse migrations failed. This is mostly caused by the database being unavailable.
Exiting...
Error: CLICKHOUSE_URL is not configured. Migrating from V2? Check out migration guide: https://langfuse.com/self-hosting/upgrade-guides/upgrade-v2-to-v3
error: failed to parse scheme from database URL: no scheme
```

### 1. Simple Setup (docker-compose.langfuse-simple.yml)
- Attempted to disable ClickHouse with `CLICKHOUSE_URL=""`
- Result: Database URL parsing errors
- Attempted to remove CLICKHOUSE_URL entirely
- Result: LangFuse v3.66.1 requires ClickHouse configuration

### 2. Full Setup (docker-compose.langfuse.yml)
- Includes PostgreSQL + ClickHouse + LangFuse
- ClickHouse container starts and becomes healthy
- PostgreSQL container starts and becomes healthy  
- LangFuse server fails during ClickHouse migrations

## Environment Details
- **Date**: June 8, 2025
- **LangFuse Version**: v3.66.1 (latest stable)
- **Docker Compose**: Using official LangFuse docker-compose configurations
- **System**: macOS with Docker Desktop
- **AcademiaOS Version**: 2.0

### Current docker-compose.langfuse.yml
```yaml
services:
  langfuse-server:
    image: langfuse/langfuse:3.66.1
    environment:
      - DATABASE_URL=postgresql://langfuse:langfuse@langfuse-db:5432/langfuse
      - CLICKHOUSE_URL=http://langfuse-clickhouse:8123
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=
      - NEXTAUTH_URL=http://localhost:3030
      - NEXTAUTH_SECRET=mysecret
      - SALT=mysalt
      - ENCRYPTION_KEY=0000000000000000000000000000000000000000000000000000000000000000
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=true
    depends_on:
      langfuse-db:
        condition: service_healthy
      langfuse-clickhouse:
        condition: service_healthy
```

## Impact
- **High Priority**: AI monitoring and cost tracking unavailable
- **Functionality Affected**: LangFuse integration in Model Configuration Advanced Options
- **Workaround**: Core AcademiaOS functionality works without LangFuse
- **Academic Impact**: No AI usage statistics or cost tracking for research projects

## Expected Behavior
- LangFuse containers start successfully
- Web interface accessible at http://localhost:3030
- Health check returns HTML/redirect (not connection refused)
- Academic statistics and cost monitoring available in AcademiaOS

## Possible Solutions to Investigate
1. **Version Compatibility**: Check if LangFuse v3.66.1 has known ClickHouse integration issues
2. **Migration Guide**: Follow V2→V3 migration steps even for fresh installations
3. **Environment Variables**: Review all required environment variables for v3.66.1
4. **Container Startup Order**: Investigate if additional startup delays needed
5. **Alternative Versions**: Test with different LangFuse versions (v3.x range)
6. **ClickHouse Configuration**: Review ClickHouse container configuration and networking

## Reproduction Steps
1. `docker-compose -f docker-compose.langfuse.yml up -d`
2. `docker ps | grep langfuse` (observe restart loop)
3. `docker logs langfuse-server` (see ClickHouse migration errors)
4. `curl http://localhost:3030` (connection refused)

## Related Documentation
- [LangFuse Self-Hosting Guide](https://langfuse.com/docs/deployment/self-host)
- [LangFuse V2→V3 Migration Guide](https://langfuse.com/self-hosting/upgrade-guides/upgrade-v2-to-v3)
- [LangFuse Docker Compose Examples](https://github.com/langfuse/langfuse/tree/main/docker)

## Labels
`bug`, `infrastructure`, `docker`, `langfuse`, `monitoring`, `high-priority`

Collaboration between A Helme and Claude
